---
- name: Update apt cache if needed.
  apt: update_cache=true cache_valid_time=3600

- name: Install Java.
  apt: name=openjdk-11-jdk state=present

- name: Download solr
  ansible.builtin.get_url: 
    url: "https://www.apache.org/dyn/closer.lua/solr/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz?action=download"
    dest: "{{ download_solr }}/solr-{{ solr_version}}.tgz"
    checksum: "{{ solr_checksum }}"

- name: Unpack solr
  ansible.builtin.unarchive:
    src: "{{ download_solr }}/solr-{{ solr_version}}.tgz"
    dest: "{{ download_solr }}"
    remote_src: true
    creates: "{{ download_solr }}/solr-{{ solr_version}}/README"

- name: Run Installation.
  command: >
    {{ download_solr }}/solr-{{ solr_version}}/bin/install_solr_service.sh
    {{ download_solr }}/solr-{{ solr_version}}.tgz
    -i /opt
    -d /var/solr
    -u solr
    -s solr
    -p 8983
  arg: 
    creates={{ solr_dir }}/bin/solr

- name: Ensure solr is started and enabled at boot.
  service: name=solr state=started enable=true
